### ISSUE TITLE
Customize the Time interval for the Refreshing of the Image and Automatic Refresh

### ISSUE THREAD

**Issue by jscmal** [BinaryMoon/browser-shots#10]
Hi, 
why do not let to users the choice to set the interval of time before to create again a screenshot?

Why do not set an automatic refresh of the image/images?

Kind regards

G.Aloe

**Comment by BinaryMoon** [comment]
Hi there - thanks for the feedback.

Unfortunately the screenshotting uses a third party api:
https://github.com/BinaryMoon/browser-shots/blob/master/src/block/edit.js#L89

They don't support custom refresh rates so there's nothing I can do to add that I'm afraid.

Thanks.

**Comment by jscmal** [comment]
Hi, thanks for your answer.

In the code, there is a variable for versioning, related to a refresh function.

Does the changing of this version parameter induce the creation of a new screenshot, without use/load the old image?

Could we use that parameter to induce a new creation of the screenshot?

Kind regards

G.Aloe
