### ISSUE TITLE
integration with an ad blocker?

### ISSUE THREAD

**Issue by pultars** [BinaryMoon/browser-shots#24]
Great plugin but screenshots are crowded with ads. The screenshots I get with the plugin are different than when I look at the page using my browser, since I use adblockers.

It would be awesome if the plugin integrated with adblockers.

Thanks.

**Comment by BinaryMoon** [comment]
Hi there - thanks for the message.

I'm afraid this isn't something that can be done. The screenshotting isn't done by a normal web browser. It's done by a headless webbrowser - which means it renders on a server and isn't displayed, and it doesn't have extensions (as far as I'm aware).

The rendering is done by a third party service run by wordpress.com and so we have no control over it.

Sorry about that.
