### ISSUE TITLE
Bug: plugin hangs on generating preview

### ISSUE THREAD

**Issue by SamuelMiller** [BinaryMoon/browser-shots#26]
I am unable to get the browser shot plugin to work in Wordpress 5.9, locally or online at Bluehost. After I add an URL in the block editor, the displayed image hangs on "Generating Preview", never completing its task.

**Comment by SamuelMiller** [comment]
I read the FAQ, and it said to "refresh" the image in the editor which I did and it fixed the problem.

**Comment by BinaryMoon** [comment]
Hey - thanks for the report. Unfortunately there's no easy way to refresh the images automatically. We could change it so they refresh but they would do it forever since we don't know if the image is generated or not - which is why there's a refresh button in the block toolbar.
