### ISSUE TITLE
Multiple URLs and Slideshow Capability

### ISSUE THREAD

**Issue by ronaldhuereca** [BinaryMoon/browser-shots#8]
This could be released as a separate paid add-on.

**Comment by BinaryMoon** [comment]
Hey Ron - that's an interesting suggestion. Do you think many people would want to use this?

**Comment by ronalfy** [comment]
Not sure. I'm sure it'll be useful for portfolio websites.

**Comment by BinaryMoon** [comment]
That's true. Might work if it was marketed as being ideal for portfolios. I'll think about this.
